"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.descriptor_pb2
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.internal.extension_dict
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _APISourceType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _APISourceTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_APISourceType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SOURCE_BOTH: _APISourceType.ValueType  # 0
    SOURCE_SERVER: _APISourceType.ValueType  # 1
    SOURCE_CLIENT: _APISourceType.ValueType  # 2

class APISourceType(_APISourceType, metaclass=_APISourceTypeEnumTypeWrapper): ...

SOURCE_BOTH: APISourceType.ValueType  # 0
SOURCE_SERVER: APISourceType.ValueType  # 1
SOURCE_CLIENT: APISourceType.ValueType  # 2
global___APISourceType = APISourceType

@typing.final
class void(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___void = void

NEEDS_SETUP_CONNECTION_FIELD_NUMBER: builtins.int
NEEDS_AUTHENTICATION_FIELD_NUMBER: builtins.int
ID_FIELD_NUMBER: builtins.int
SOURCE_FIELD_NUMBER: builtins.int
IFDEF_FIELD_NUMBER: builtins.int
LOG_FIELD_NUMBER: builtins.int
NO_DELAY_FIELD_NUMBER: builtins.int
needs_setup_connection: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.MethodOptions, builtins.bool]
needs_authentication: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.MethodOptions, builtins.bool]
id: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.MessageOptions, builtins.int]
source: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.MessageOptions, global___APISourceType.ValueType]
ifdef: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.MessageOptions, builtins.str]
log: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.MessageOptions, builtins.bool]
no_delay: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.MessageOptions, builtins.bool]
